#version: "3.7"
x-api: &default-api
  image: ghcr.io/stssocialst-stp/kenon-backend:latest
  build: 
    context: ./openimis-be_py/
    dockerfile: Dockerfile
  environment:
    - DB_DEFAULT=${DB_DEFAULT:-postgresql}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - SITE_ROOT=api
    - SITE_URL=${DOMAIN}
    - CELERY_BROKER_URL=amqp://rabbitmq
    - MODE=${MODE:-Prod}
    - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
  volumes:
    - photos:/kenon-backend/openIMIS/images/insurees
  depends_on:
    db:
      condition: service_healthy
  networks:
    openimis-net:
  restart: always

services:
  frontend:
    container_name: kenon-frontend
    image: ghcr.io/stssocialst-stp/kenon-frontend:latest
    build: 
      context: ./openimis-fe_js/
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - REACT_APP_API_URL=api
      - NEW_OPENIMIS_HOST=${DOMAIN}
      - OPENIMIS_CONF_JSON=${OPENIMIS_FE_CONF_JSON}
      - OPENSEARCH_BASIC_TOKEN=${OPENSEARCH_BASIC_TOKEN}
    networks:
      openimis-net:
    ports:
      - 4005:80    # frontend HTTP
      - 4006:443   # frontend HTTPS
    depends_on:
      - backend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./conf/nginx:/conf/

  backend:
    <<: *default-api
    container_name: kenon-backend
    command: start
    env_file: .env
    ports:
      - 4007:8000   # backend exposto na porta 4007

  worker:
    <<: *default-api
    container_name: kenon-worker
    command: worker
    env_file: .env
    ports:
      - 4009:8000   # worker exposto na porta 4009

  rabbitmq:
    container_name: kenon-rabbitmq
    image: rabbitmq:3-management
    restart: always
    networks:
      openimis-net:
    ports:
      - 4008:5672   # rabbitmq exposto na porta 4008

networks:
  openimis-net:
    name: kenon-net

volumes:
  database:
  photos:
