name: Deploy Frontend
on:
  repository_dispatch:
    types: deploy-kenon-frontend
jobs:
  deploy-frontend:
      runs-on: self-hosted
      steps:
        - name: Checkout repo central
          uses: actions/checkout@v3
  
        - name: Deploy frontend
          run: |
            cd $GITHUB_WORKSPACE
            docker compose -f docker-compose.base.yml pull frontend
            docker compose -f docker-compose.base.yml up -d frontend
