name: Deploy Kenon Frontend

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'latest'
        required: true
        default: 'latest'

jobs:
  deploy-frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout repo central
        uses: actions/checkout@v3

      - name: Deploy frontend
        run: |
          cd /app
          docker compose pull frontend:${{ github.event.inputs.image_tag }}
          docker compose up -d frontend