name: Deploy Backend
on:
  repository_dispatch:
    types: deploy-kenon-backend
jobs:
  deploy-backend:
      runs-on: self-hosted
      steps:
        - name: Checkout repo central
          uses: actions/checkout@v3
  
        - name: Deploy backend
          run: |
            cd $GITHUB_WORKSPACE
            docker compose -f docker-compose.base.yml pull backend
            docker compose -f docker-compose.base.yml up -d backend
